export const EditorHover = 'EditorHover'
export const HoverDisplayString = 'HoverDisplayString'
export const HoverDocumentation = 'HoverDocumentation'
export const HoverEditorRow = 'HoverEditorRow'
export const HoverProblem = 'HoverProblem'
export const HoverProblemDetail = 'HoverProblemDetail'
export const HoverProblemMessage = 'HoverProblemMessage'
export const Viewlet = 'Viewlet'
